[package]
name = "cucumber_rust"
version = "0.6.7"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
description = "Cucumber testing framework for Rust. Fully native, no external test runners or dependencies."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/bbqsrc/cucumber-rust"
documentation = "https://docs.rs/cucumber_rust"
homepage = "https://github.com/bbqsrc/cucumber-rust"
edition = "2018"

[badges]
travis-ci = { repository = "bbqsrc/cucumber-rust" }

[[test]]
name = "cucumber_builder"
harness = false

[dependencies]
gherkin = { package = "gherkin_rust", version = "^0.7.0" }
regex = "1.3.3"
termcolor = "1.1.0"
pathdiff = "0.1.0"
textwrap = { version = "0.11", features = ["term_size"] }
clap = "2.33.0"
globwalk = "0.7"
shh = "1.0.1"
futures = "0.3"
pin-utils = "0.1.0-alpha.4"
indicatif = "0.13.0"
